### ISSUE TITLE
IE8 https issue

### ISSUE THREAD

**Issue by McGern** [mahnunchik/markerclustererplus#1]
Probably the wrong place post this, but couldn't work out the google repository stuff.

Had been pulling my hair out with an IE8 "mixed content" issue over https. Turns out the problems was a bug in IE8- where element with background image that are removed using removeChild trigger the "mixed content" message. Simple fix was to put this in the ClusterIcon onRemove method before the removeChild call

this.div_.style.backgroundImage = "none";

So the full method reads:

ClusterIcon.prototype.onRemove = function () {
    if (this.div_ && this.div_.parentNode) {
        this.hide();
        google.maps.event.clearInstanceListeners(this.div_);
        this.div_.style.backgroundImage = "none";
        this.div_.parentNode.removeChild(this.div_);
        this.div_ = null;
    }
};

**Comment by ahaarnos** [comment]
I'm also interested in this issue, which seems to have been open in the parent project in some form or fashion for years: https://code.google.com/p/google-maps-utility-library-v3/issues/detail?id=225

As-is, the code is using Google Code's browsable SVN as a CDN if you don't provide an `imagePath` property in the `opt_options` (third argument) of the `MarkerClusterer` constructor call when using it. I know Github doesn't like being used as a CDN, so I imagine Google's not very fond of it either.

In my current company's usage, we're going to fix the issues we're seeing by properly configuring the plugin in our usages, but I'm willing to open a pull-request targeting this repo with a fix to the default behavior for this since it seems like the parent project is pretty inert at this point.

**Comment by mahnunchik** [comment]
@ahaarnos PRs welcome :wink:
